### ISSUE TITLE
(Idea) Region and Chat not preselected

### ISSUE THREAD

**Issue by ppfeufer** [Xanthos-Eve/vintel#53] opened 2016-01-28 18:39 UTC
Just as an Idea to spread this awesome tool more within the EVE community.

**Region Selection:**

- Don't select Providence by default instead have a little notice box to set the region, if not already a region is selected.
- Every Region as checkbox.

**Chat Settings:**

- Don't set "our" intels as default instead have a little notice box to set the intel channels (and how, maybe also open the channel settings), as long as there is no channel set

All in all, some sort of step by step setup for the first start, or as long as there are some important settings missing, like region or channels to monitor would be nice to have. I think with that this great tool could have the potential to reach more players within EVE ...

**Comment by ppfeufer** [comment] 2016-01-28 18:43
Same goes in this case obviously for the JB map data. I think dotlan has some sort of standardized format for this, including planet and moon the JB is on.

**Comment by Xanthos-Eve** [comment] 2016-02-02 04:02
Yeah I'll look at the JB format after I get the combined map sorted. I know what the issue is now with the combined map - it is a hand edited version of a merged map with transforms applied fro certain systems, but the JB and Current Location use the untransformed coordinates - I have to make them use the transform when laying them out.

**Comment by Xanthos-Eve** [comment] 2016-07-03 18:26
Incorporating into the wiki

**Closed by Xanthos-Eve** 2016-07-03 18:26 UTC
Labels: enhancement
