### ISSUE TITLE
Pop ups Doesn't work

### ISSUE THREAD

**Issue by ALNeNesterov** [Xanthos-Eve/vintel#76] opened 2016-05-08 21:22 UTC
error.log

--------------------------------------------------------------------------------
2016-04-24, 16:56:49
--------------------------------------------------------------------------------
<class 'urllib2.HTTPError'>: 
HTTP Error 404: Not Found
--------------------------------------------------------------------------------
  File "<string>", line 140, in <module>
  File "<string>", line 132, in main
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\vi.ui.viui", line 60, in __init__
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\vi.dotlan", line 68, in __init__
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\vi.dotlan", line 150, in _get_svg_from_web
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\urllib2", line 154, in urlopen
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\urllib2", line 437, in open
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\urllib2", line 550, in http_response
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\urllib2", line 475, in error
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\urllib2", line 409, in _call_chain
  File "c:\Users\Nick\Dropbox\Projecten\Vintel\build\vintel\out00-PYZ.pyz\urllib2", line 558, in http_error_default
0.52

output.log

05/06 12:19:41| 
05/06 12:19:41| ------------------- Vintel 1.1.2 starting up -------------------
05/06 12:19:41| 
05/06 12:19:41| 'MainWindow' object has no attribute 'changeClipboard'
05/06 12:19:41| 'MainWindow' object has no attribute 'changeFloatingOverview'
05/06 12:19:41| 'MainWindow' object has no attribute 'changeAlreadyShowedSoundWarning'
05/06 12:19:42| Load jump bridges
05/06 12:19:44| Creating chat parser
05/06 12:19:44| Initializing contextual menus
05/06 12:19:44| Updating the map
05/06 12:19:46| Map setup complete
05/06 12:29:10| SoundThread.playAudioFile exception: Not a WAVE file
05/06 12:36:22| SoundThread.playAudioFile exception: Not a WAVE file
05/06 12:46:58| SoundThread.playAudioFile exception: Not a WAVE file
05/06 01:18:11| SoundThread.playAudioFile exception: Not a WAVE file
05/06 02:13:41| Exception turning charname to id via API: HTTP Error 503: Service Unavailable
05/06 02:13:43| Exception turning charname to id via API: HTTP Error 503: Service Unavailable
05/07 11:49:21| 
05/07 11:49:21| ------------------- Vintel 1.1.2 starting up -------------------
05/07 11:49:21| 
05/07 11:49:21| Load jump bridges
05/07 11:49:24| Creating chat parser
05/07 11:49:24| Initializing contextual menus
05/07 11:49:24| Updating the map
05/07 11:49:26| Map setup complete
05/07 10:56:37| SoundThread.playAudioFile exception: Not a WAVE file
05/08 02:13:15| 
05/08 02:13:15| ------------------- Vintel 1.1.2 starting up -------------------
05/08 02:13:15| 
05/08 02:13:16| Load jump bridges
05/08 02:13:18| Creating chat parser
05/08 02:13:18| Initializing contextual menus
05/08 02:13:18| Updating the map
05/08 02:13:20| Map setup complete
05/08 06:18:39| Exception turning charname to id via API: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
05/08 06:19:11| Exception during getAvatarForPlayer: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
05/08 06:19:35| Exception during getAvatarForPlayer: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
05/08 06:20:16| Exception turning charname to id via API: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
05/08 06:20:38| Exception during getAvatarForPlayer: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
05/08 08:04:41| SoundThread.playAudioFile exception: Not a WAVE file
05/08 11:26:50| SoundThread.playAudioFile exception: Not a WAVE file

**Comment by Xanthos-Eve** [comment] 2016-05-14 01:35
Where do I begin? so many things going wrong here. Could the download be corrupt or are you out of disk / memory? I see http errors - do you have an unreliable connection?

**Comment by ALNeNesterov** [comment] 2016-05-16 23:31
Sry for my weak English )
1. 

> Could the download be corrupt or are you out of disk / memory?

Well, I downloaded it here and it`s launching and working well (except of the notification popups), don`t understand how could it be corrupt then, but I`m not the specialist.
Every disk I have have free space. It happens I'm running out of 32gb ram sometimes when i'm working on  big projects for my work while I have 2 eve clients launched too, but it's very seldom.
2. 

> I see http errors - do you have an unreliable connection?

Well, it happens about once in a month when I can`t access any website for several minutes, maybe twice, but again, I don`t think it is the reason I don`t have popups.

 I should add Vintel to firewall whitelist I think, but I don`t think this might help with notifications.
I have an old version of vintel too (the one that CopyCatz adopted for catch) and for some time I was using it together with your version to see witch one is the best, could this be a reason of the problem? If so, should I do smth "special" to fix it? Clear windows registry or smth?

**Comment by Xanthos-Eve** [comment] 2016-05-17 00:21
Ok network issues are not connected, not sure what to make of the audio exception

The old Vintel and the new one use separate databases so there should not be conflicts using both. You could try setting your cache file aside - quit vintel, move the cache file out of the directory or throw it away, restart vintel. You will have to change the settings to your liking but it may be worth a try.

**Comment by Xanthos-Eve** [comment] 2016-05-17 00:22
I work on a Mac - looks like I will need to spend some time on the windows machine to understand this.

**Comment by Xanthos-Eve** [comment] 2016-06-27 00:31
I have been testing on my Win7 box and have been unable to reproduce this. Closing for now - reopen or create a new ticket if the issue persists.

**Closed by Xanthos-Eve** 2016-06-27 00:31 UTC
Labels: bug
