### ISSUE TITLE
character location isnt showing in win platform?

### ISSUE THREAD

**Issue by chriz3W** [Xanthos-Eve/vintel#16] opened 2016-01-03 09:40 UTC
There seems to be a glitch not showing your own users on the map any more. reproduce by warping to a gate and jump thru and repeat it doesnt show.

**Comment by chriz3W** [comment] 2016-01-03 10:03
this code is being run and runs fine ...

	def addLocatedCharacter(self, charname):
		idName = self.name + u"_loc"
		wasLocated = bool(self.__locatedCharacters)
		if charname not in self.__locatedCharacters:
			self.__locatedCharacters.append(charname)
		if not wasLocated:
			coords = self.mapCoordinates
			newTag = self.mapSoup.new_tag(
				"ellipse", cx=coords["center_x"]-2.5, cy=coords["center_y"],
				id=idName, rx=coords["width"]/2+4, ry=coords["height"]/2+4,
				style="fill:#8b008d")
			jumps = self.mapSoup.select("#jumps")[0]
			jumps.insert(0, newTag)

but it doesnt do anything for some reason I am still trying to figure out why it isnt writing anything on the map. the like jumps = self.mapSoup.select("#jumps")[0] looks scray and will fail if there isnt anything in that array at all no check for size or anything is being done. It wouldnt be empty any how but perfect is perfect :P

**Comment by chriz3W** [comment] 2016-01-03 21:51
I know now why ... its because I am using the "ProvidenceCatch" region and it will of course work if I use the "Catch" region or the "Providence" region but not in conjunction.

not sure how the dotlan map looks like but would guess that the tree structure from where you start to pinpoint my location isnt matching the "ProvidenceCatch" dotlan map.

Further debuggning ongoing.

/chriz

**Comment by Xanthos-Eve** [comment] 2016-01-19 05:42
Duplicate of another issue

**Closed by Xanthos-Eve** 2016-01-19 05:42 UTC
Labels: bug
